NTLS证书问题
Tongsuo-Project/tongsuo-go-sdk pull request #24
Opened 2024-07-24 14:21 UTC by ZBCccc

2024-07-27 15:02 UTC, dongbeiouba requested changes
测试生成的证书私钥不要覆盖代码仓库的文件，可以用临时的名字，最后清理。然后用生成的私钥和证书文件再测试TLCP（ntls）。

需要增加Example，签发签名和加密双证书。

2024-07-28 06:08 UTC, ZBCccc commented on ntls_test.go
> +			caFile:    filepath.Join(testCertDir, "chain-ca1.crt"),
因为加1的文件就是我生成的新的文件。

2024-07-28 06:09 UTC, ZBCccc commented on crypto/cert_test.go
> +	caKey := generateAndSaveKey("./../test/certs/sm2/ca.key")
没有覆盖仓库中已有的文件，新生成的文件都是在原有文件的命名基础上加1

2024-07-28 06:24 UTC, ZBCccc commented on crypto/key.go
> +	runtime.KeepAlive(key)
runtime.KeepAlive(key)确保在转换过程中,key对象不会被垃圾回收。

2024-08-03 03:28 UTC, closed without merging