tongsuo NTLS client wrapper
Tongsuo-Project/tongsuo-go-sdk pull request #3
Opened 2023-06-06 16:42 UTC by itomsawyer

Test with Tongsuo 8.3.2

Support NTLS "ECC-SM2-WITH-SM4-SM3" client

2023-06-07 02:23 UTC, dongbeiouba requested changes

2023-06-07 02:23 UTC, dongbeiouba commented on ntls_test.go
> +Host: demo.gmssl.cn
请用Tongsuo构建的s_server来起一个服务端

2023-06-07 02:23 UTC, dongbeiouba commented on ntls_test.go
> +User-Agent: tongsuog
tongsuog -> tongsuogo或者tongsuo-go-sdk

2023-07-04 09:50 UTC, itomsawyer commented on ntls_test.go
> +User-Agent: tongsuog
Removed HTTP like request , use simple echo request instead

2023-07-04 09:51 UTC, itomsawyer commented on ntls_test.go
> +Host: demo.gmssl.cn
Use golang listener to wrapper a Tongsuo NTLS server

2023-07-06 03:24 UTC, dongbeiouba approved these changes
LGTM

2023-07-06 03:26 UTC, merged